---

services:
  app:
    build: .
    volumes:
      - ./:/opt/app:delegated
    environment:
      SOLR_URL: http://solr:8983/solr/geodata-test

      # Separated geoserver urls
      # GEOSERVER_URL: http://admin:geoserver@host.docker.internal:8080/geoserver/rest/
      # GEOSERVER_SECURE_URL: http://admin:geoserver@host.docker.internal:8080/geoserver/rest/

      GEOSERVER_URL: http://admin:geoserver@geoserver:8080/geoserver/rest/
      GEOSERVER_SECURE_URL: http://admin:geoserver@geoserver:8080/geoserver/rest/

      DOWNLOAD_URL: https://spatial.lib.berkeley.edu/

      SPATIAL_ROOT: data/spatial/
      GEOSERVER_ROOT: data/geoserver/

  solr:
    image: solr:${SOLR_VERSION:-8.11.1}
    restart: always
    ports:
      - 8983:8983
    volumes:
      - ./solr:/var/solr/data/configsets/solr:delegated

  geoserver:
    image: containers.lib.berkeley.edu/gis/geoserver/v2.23.2
    ports:
      - 8080:8080
    volumes:
      - ./data/geoserver/public:/srv/geofiles:delegated

version: "3.7"
