---

services:
  app:
    build: .
    volumes:
      - ./:/opt/app:delegated
    environment:
      SOLR_URL: http://solr:8983/solr/geodata-test
      GEOSERVER_SECURE_URL: http://admin:geoserver@localhost:8080/geoserver/rest/
      GEOSERVER_URL: http://admin:geoserver@localhost:8080/geoserver/rest/
      DOWNLOAD_URL: https://spatial.lib.berkeley.edu/

  solr:
    image: solr:${SOLR_VERSION:-8.11.1}
    restart: always
    ports:
      - 8983:8983
    volumes:
      - ./solr:/var/solr/data/configsets/solr:delegated

version: "3.7"
