---

services:
  app:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    volumes: !override
      - artifacts:/opt/app/artifacts

  geoserver: !reset

  geoserver-secure: !reset
  
volumes:
  artifacts:
